#!/bin/sh

### BEGIN INIT INFO
# Provides:          fll-shell
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: configure shell
# Description:       Populate /root/.bash* for a more comfortable root shell
#                    login. Preset some shell application settings.
### END INIT INFO

###
# F.U.L.L.S.T.O.R.Y init script
#
# Copyright: (C) 2007 - 2008 Kel Modderman <kel@otaku42.de>
# License:   GPLv2
#
# F.U.L.L.S.T.O.R.Y Project Homepage:
# http://developer.berlios.de/projects/fullstory
###

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME="fll-shell"

###
# source distro-defaults, no-op unless in live mode
###
FLL_DISTRO_MODE="installed"

if [ -r /etc/default/distro ]; then
	. /etc/default/distro
fi

if [ "${FLL_DISTRO_MODE}" != "live" ]; then
	exit 0
fi

###
# VERBOSE setting and other rcS variables
###
#. /lib/init/vars.sh

###
# source lsb functions

###
. /lib/lsb/init-functions

###
# source fll functions
###
. /lib/init/fll

###
# cheatcode handling
###
if [ -f /proc/cmdline ]; then
	for param in $(cat /proc/cmdline); do
		case "${param}" in
			flldebug=*)
				if [ "${param#flldebug=}" = "${NAME#fll-}" ] || [ "${param#flldebug=}" = "all" ]; then
					fll_redirect
				fi
				;;
		esac
	done
fi

do_start() {
	for file in '.bash_logout' '.bash_profile' '.bashrc' '.profile'; do
		if [ -f /etc/skel/${file} ] && [ ! -f /root/${file} ]; then
			cp /etc/skel/${file} /root/${file}
		fi
	done

	:> /root/.hushlogin

	if [ -w /etc/pam.d/login ]; then
		sed -i '/^[^#].*pam_lastlog\.so/s/^/# /' /etc/pam.d/login
	fi
}

case "${1}" in
	start)
		do_start
		;;
	stop)
		;;
	restart|force-reload)
		echo "Error: argument '${1}' not supported" >&2
		exit 3
		;;
	status)
		log_success_msg "${0} is no dæmon."
		exit 0
		;;
	*)
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 3
		;;
esac

:
